name: re_fashion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  firebase_cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  flutter_barcode_scanner: ^2.0.0
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.69.2
  excel: ^4.0.6
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  firebase_storage: 12.3.6

dev_dependencies:
  flutter_launcher_icons: 0.14.1
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff" # Aquí coloca el color de fondo que deseas
  image: assets/icon/icon.png # Usa el mismo ícono que ya configuraste
  android: true
  ios: false # Si estás desarrollando solo para Android
  web: false
