name: re_fashion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.0
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.3
  flutter_barcode_scanner: ^2.0.0
  font_awesome_flutter: ^10.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff" # Aquí coloca el color de fondo que deseas
  image: assets/icon/icon.png # Usa el mismo ícono que ya configuraste
  android: true
  ios: false # Si estás desarrollando solo para Android
  web: false
